### ISSUE TITLE
Considering support setjmp & longjmp?

### ISSUE THREAD

**Issue by Brooooooklyn** [toyobayashi/emnapi#109]
`setjmp.h` is not supported in `wasi-libc` at this moment: https://github.com/WebAssembly/wasi-libc/issues/432
If you could support `setjmp.h` in emnapi, it would be very useful for C++ projects compiled to wasi target, such as https://github.com/AOMediaCodec/libavif.

For references:
- wasix implemented `setjmp.h` here: https://github.com/wasix-org/wasix-libc/blob/main/libc-bottom-half/sources/__wasilibc_stack.c
- https://twitter.com/kripken/status/1173993718262534145

**Comment by toyobayashi** [comment]
OK. Though I think setjmp/longjmp is out of the scope of emnapi, I'll investigate how it works in WASIX and Emscripten, then consider providing prebuilt static library as temporary solution before wasi-libc have it.

Happy dragon new year!

**Comment by toyobayashi** [comment]
WASIX and kripken's demo rely on the [Asyncify](https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html) feature of binaryen, which will affect runtime performance and increases code size.

[Emscripten has two implementation of setjmp/longjmp](https://emscripten.org/docs/porting/setjmp-longjmp.html), the default way relies on generated JavaScript glue code by emcc, the other relies on [WebAssembly Exception Handling](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md) feature, they both require passing additional flags to llvm backend to let llvm transform the `setjmp()` / `longjmp()` call to additional runtime code.

I've created a separate repository (https://github.com/toyobayashi/wasm-sjlj) to test if the wasm EH way works in WASI, included the prebuilt libraries. I used the implementation in emscripten repo, and [pass `-mllvm -wasm-enable-sjlj`](https://github.com/toyobayashi/wasm-sjlj/blob/f42261109335cfcdd8b0d52d371d67acffc930da/build.sh#L68), it looks good. Since it is not relative with Node-API, I'm not sure if it should go emnapi's repo.

Refs:

- https://reviews.llvm.org/D115893
- https://github.com/llvm/llvm-project/blob/586ecdf205aa8b3d162da6f955170a6736656615/llvm/lib/Target/WebAssembly/WebAssemblyLowerEmscriptenEHSjLj.cpp#L187

Could you try it to build libavif?

**Comment by Brooooooklyn** [comment]
@toyobayashi it works! thanks for your help!

**Comment by Brooooooklyn** [comment]
Can you publish a npm package that contains `lib/libsetjmp.a` `lib/libsetjmp-mt.a` and `include/setjmp.h` files?

**Comment by toyobayashi** [comment]
Done. https://www.npmjs.com/package/wasm-sjlj
