### ISSUE TITLE
Error hadling

### ISSUE THREAD

**Issue by DavidGOrtega** [toyobayashi/emnapi#47]
👋 @toyobayashi my library (that you already know) runs in worker. How can I catch the errors coming from it?
Can I setup worker.onerror?

Here is my returned error:

```
worker sent an error! http://localhost:8081/hnswlib.worker.js:1: Uncaught 18952616
```

**Comment by toyobayashi** [comment]
Sorry, your description is too short and lacks context, I don't know the exact implementation detail of your code so I can't give you a meaningful response.

For example, when I see this issue description, I'd like to know what "runs in worker" means, I will guess

- Are you calling the library function in `async_work` (async work runs in pthread worker if you link `libemnapi-mt.a`)?
- Are you running your whole program in worker (something like `-sPROXY_TO_WORKER` / `-sPROXY_TO_PTHREAD`)?

About the error, I also don't know whether it is throw by emnapi itself or throw by your library / caller code and what it is.

So before you create an issue I suggest you provide a minimum reproduce in a public repository with clear step (how to build, how to run, what to do to reproduce this error), so that we could make things more clear.

**Comment by DavidGOrtega** [comment]
sorry if I have not been clear 🙏 

With my library that you already did a test I have found that readIndex cant be caught while other promisified responses can.

```html
</script>
    <script src="hnswlib.js"></script>
    <script src="node_modules/@emnapi/runtime/dist/emnapi.min.js"></script>
    <script>
    window.onload = async (e) => {
      const { getDefaultContext } = emnapi;
      const Mod = await hnswlib();
      const { HierarchicalNSW } = Mod.emnapiInit({ context: getDefaultContext() });

      try {
        const numDimensions = 8
        const index = new HierarchicalNSW('l2', numDimensions);
        await index.readIndex('i_do_not_exist');
      } catch (err) {
        console.log('I should be displayed', err)
      }
    }
    </script>
```
<img width="773" alt="image" src="https://user-images.githubusercontent.com/414967/229858353-42e44812-3ea0-4d9c-94f8-c712ffab3b7b.png">


My simple question was why its not being caught and if there is any mechanism like worker.onerror

**Comment by toyobayashi** [comment]
I see your library does use C++ exceptions, `throw std::runtime_error("failed to open file: " + filename);`, so you should enable C++ exception in your build flags.

**Comment by DavidGOrtega** [comment]
Ok, I was wandering why for other methods the exception was caught. Now seems to be working in every single one.
Thanks! 🙏
